### ISSUE TITLE
Page descriptions

### ISSUE THREAD

**Issue by ekes** [events-radar/drupal-make#133]
It would be nice in addition to [#124] the facets being in the title that the page has a description. Something like
'Radical events [in XXX] [about XXX]'

**Comment by ifrik** [comment]
Each facet needs a different prefix then
- in City
- in Country (or nothing so that we get "in Amsterdam, Netherlands" rather then "in Amsterdam, in Netherlands)
- by Group
- for Price
- in Year
- in Month
- on Day
  I'm not quite sure what to add for categories and tags though.

**Comment by ekes** [comment]
Loading the facets is a right pain see the code in the new function radar_search_facets https://github.com/events-radar/drupal-make/commit/6bff1fe34e455cce40f3e30f5f3f7372fa47927c so the string may as well be constructed based on what's loaded in radar_search_preprocess_page() and just added to the render array for the meta description there.

**Comment by ekes** [comment]
Deployed
